name: Frontend Pigeon Sky Race CI/CD Pipeline

on:
  push:
    branches:
      - test
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci 

      - name: Run Unit Tests
        working-directory: ./frontend
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build --configuration=production

      - name: Build Docker Image
        run: docker build -t frontend-app ./frontend
