name: Frontend Pigeon Sky Race CI/CD Pipeline

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t pigeon-sky-race-frontend ./frontend
          docker run --rm pigeon-sky-race-frontend npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Frontend Docker Image
        run: |
          docker build -t pigeon-sky-race-frontend ./frontend
          
  deploy:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
